export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';

export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';

export const GET_FRIENDSHIP_SUCCESS = 'GET_FRIENDSHIP_SUCCESS';
