export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
export const GET_IF_LOGGED_IN_SUCCESS = 'GET_IF_LOGGED_IN_SUCCESS'
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const CHECK_IF_LOGGED_SUCCESS = 'CHECK_IF_LOGGED_SUCCESS'

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_ALL_PHOTOS_SUCCESS = 'GET_ALL_PHOTOS_SUCCESS'
export const SEND_PHOTO_SUCCESS = 'SEND_PHOTO_SUCCESS';

export const GET_FRIENDSHIP_SUCCESS = 'GET_FRIENDSHIP_SUCCESS';
export const SEND_FRIENDSHIP_REQUEST_SUCCESS = 'SEND_FRIENDSHIP_REQUEST_SUCCESS';
